mod instructions;
use anyhow::Result;
use clap::{Parser, Subcommand};
use instructions::{deploy_airdrop, get_default_keypair_path, get_default_program_id, DeployAirdropArgs, Network};
use std::path::PathBuf;
use std::str::FromStr;

#[derive(Parser)]
#[command(author, version, about = "Solana Easy Airdrop CLI")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Construct a Merkle-tree from a CSV file that contains `address,amount` rows.
    /// Outputs an airdrop.json file for use with the server and deploy command.
    CreateMerkleTree {
        /// Path to CSV file (with header `address,amount`)
        #[arg(long, value_name = "FILE")]
        input: PathBuf,
    },

    /// Deploy an airdrop on-chain using a previously generated airdrop.json file.
    DeployAirdrop {
        /// Path to airdrop.json file generated by create-merkle-tree
        #[arg(long, value_name = "FILE")]
        json: PathBuf,

        /// Token mint address for the airdrop
        #[arg(long)]
        mint: String,

        /// Total amount of tokens to transfer to the airdrop vault
        #[arg(long)]
        amount: u64,

        /// Network to deploy to (devnet, testnet, mainnet)
        #[arg(long, default_value = "devnet")]
        network: String,

        /// Program ID (defaults to the deployed airdrop contract)
        #[arg(long)]
        program_id: Option<String>,

        /// Path to keypair file (defaults to ~/.config/solana/id.json)
        #[arg(long)]
        keypair: Option<PathBuf>,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::CreateMerkleTree { input } => {
            instructions::create_airdrop(&input)?;
        }
        Commands::DeployAirdrop {
            json,
            mint,
            amount,
            network,
            program_id,
            keypair,
        } => {
            let network = Network::from_str(&network)?;
            let program_id = program_id.unwrap_or_else(get_default_program_id);
            let keypair_path = keypair.unwrap_or_else(get_default_keypair_path);

            deploy_airdrop(DeployAirdropArgs {
                json_path: json,
                mint,
                amount,
                network,
                program_id,
                keypair_path,
            })?;
        }
    }
    Ok(())
}
